# Generated by Django 4.2 on 2026-01-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateReservation", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("confirmée", "Confirmée"),
                            ("en_attente", "En Attente"),
                            ("annulée", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("present", models.BooleanField(default=False)),
                (
                    "id_Cour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="courses.cours",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reservations",
            },
        ),
    ]
