# Generated by Django 4.2 on 2026-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("dateEnvoi", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Notifications",
                "ordering": ["-dateEnvoi"],
            },
        ),
    ]
